import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

const VERIFICATION_NOTE =
  "This simulation was generated by an AI digital twin model and requires verification by a qualified researcher or environmental scientist before use in any decision-making context.";

const simResultsValidator = v.object({
  catchmentAreaHa:     v.optional(v.number()),
  forestRecoveryPct:   v.optional(v.number()),
  erosionRateTPerHaYr: v.optional(v.number()),
  erosionRiskLabel:    v.optional(v.string()),
  erosionTotalLoadTYr: v.optional(v.number()),
  floodFlowM3s:        v.optional(v.number()),
  contaminantConcNorm: v.optional(v.number()),
  contaminantEdgeConc: v.optional(v.number()),
});

export const addSimulation = mutation({
  args: {
    name:       v.string(),
    lat:        v.number(),
    lon:        v.number(),
    sensorType: v.union(v.literal("forest"), v.literal("erosion"),
                        v.literal("water"),  v.literal("flood")),
    elevationM: v.number(),
    slopeDeg:   v.number(),
    radiusM:    v.number(),
    simulationResults: simResultsValidator,
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("userSimulations", {
      name:              args.name,
      lat:               args.lat,
      lon:               args.lon,
      sensorType:        args.sensorType,
      elevationM:        args.elevationM,
      slopeDeg:          args.slopeDeg,
      radiusM:           args.radiusM,
      simulationResults: args.simulationResults,
      needsVerification: true,
      verificationNote:  VERIFICATION_NOTE,
      placedAt:          Date.now(),
    });
  },
});

export const removeSimulation = mutation({
  args: { id: v.id("userSimulations") },
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id);
  },
});

export const listSimulations = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db
      .query("userSimulations")
      .withIndex("by_placed_at")
      .order("desc")
      .take(50);
  },
});
